apiVersion: v1
kind: Service
metadata:
  name: akka-http
  labels:
    app: akka-http
spec:
  type: LoadBalancer
  selector:
    app: akka-http
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  - port: 8081
    protocol: TCP
    targetPort: 8081
